### ISSUE TITLE
Testing logistic regression framework

### ISSUE THREAD

**Issue by jmason-ebi** [mpi2/stats_working_group#33]
This is the working example from the FE dataset.  It has enough variation to satisfy the requirements for LR.  We had to remove rows 272, 273 due to missing data before the LR would run -- otherwise it errors with the following:

Error in data.frame(x, res) : 
  arguments imply differing number of rows: 910, 908

df <- read.csv("test_categorical_normal.csv")
p<-PhenList(df, testGenotype="Aff3/Aff3")
result <- testDataset(p, depVariable='Fusion.Of.Vertebrae', method="LR", baselineLevel="No")
vectorOutput(result)

Need to add additional checks to filter out NA rows appropriately.

We also need to rename the parserOutputSummary for the LR to be unique from the already existing parser function for MM.

**Comment by natacourby** [comment]
Done by Natasha
